In [1]:
import torch

# Part 1: create vector and matrices

x = torch.tensor(
    [1, 2, 3],
    dtype=torch.float32
)

A = torch.tensor(
    [
        [1, 2, 0],
        [0, 1, 3],
        [2, 0, 1],
    ],
    dtype=torch.float32
)

B = torch.tensor(
    [
        [1, 0, 2],
        [3, 1, 0],
        [0, 2, 1],
    ],
    dtype=torch.float32
)

print("x shape:", x.shape)
print("A shape:", A.shape)
print("B shape:", B.shape)

# Part 2(a): row sums
row_sums = A.sum(dim=1)
print("\nRow sums of A:")
print(row_sums)

# Part 2(b): column sums
col_sums = A.sum(dim=0)
print("\nColumn sums of A:")
print(col_sums)

# Part 2(c): matrix product AB
AB = A @ B
print("\nAB:")
print(AB)

# Part 2(d): matrix-vector product Ax
Ax = A @ x
print("\nAx:")
print(Ax)

# Part 2(e): scalar x^T A x
xTAx = x @ A @ x
print("\nx^T A x:")
print(xTAx)

x shape: torch.Size([3])
A shape: torch.Size([3, 3])
B shape: torch.Size([3, 3])

Row sums of A:
tensor([3., 4., 3.])

Column sums of A:
tensor([3., 3., 4.])

AB:
tensor([[7., 2., 2.],
        [3., 7., 3.],
        [2., 2., 5.]])

Ax:
tensor([ 5., 11.,  5.])

x^T A x:
tensor(42.)


In [2]:
import torch

A = torch.tensor(
    [
        [[1, 2],
         [3, 4]],

        [[0, 1],
         [1, 0]],

        [[2, 0],
         [0, 2]],
    ],
    dtype=torch.float32
)

x = torch.tensor(
    [1, 2],
    dtype=torch.float32
)

y = A @ x

y

tensor([[ 5., 11.],
        [ 2.,  1.],
        [ 2.,  4.]])

In [3]:
y.shape

torch.Size([3, 2])